// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: video.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoStreamer_UploadVideo_FullMethodName = "/video.VideoStreamer/UploadVideo"
)

// VideoStreamerClient is the client API for VideoStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoStreamerClient interface {
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FrameRequest, UploadStatus], error)
}

type videoStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoStreamerClient(cc grpc.ClientConnInterface) VideoStreamerClient {
	return &videoStreamerClient{cc}
}

func (c *videoStreamerClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FrameRequest, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoStreamer_ServiceDesc.Streams[0], VideoStreamer_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FrameRequest, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoStreamer_UploadVideoClient = grpc.ClientStreamingClient[FrameRequest, UploadStatus]

// VideoStreamerServer is the server API for VideoStreamer service.
// All implementations must embed UnimplementedVideoStreamerServer
// for forward compatibility.
type VideoStreamerServer interface {
	UploadVideo(grpc.ClientStreamingServer[FrameRequest, UploadStatus]) error
	mustEmbedUnimplementedVideoStreamerServer()
}

// UnimplementedVideoStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoStreamerServer struct{}

func (UnimplementedVideoStreamerServer) UploadVideo(grpc.ClientStreamingServer[FrameRequest, UploadStatus]) error {
	return status.Error(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedVideoStreamerServer) mustEmbedUnimplementedVideoStreamerServer() {}
func (UnimplementedVideoStreamerServer) testEmbeddedByValue()                       {}

// UnsafeVideoStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoStreamerServer will
// result in compilation errors.
type UnsafeVideoStreamerServer interface {
	mustEmbedUnimplementedVideoStreamerServer()
}

func RegisterVideoStreamerServer(s grpc.ServiceRegistrar, srv VideoStreamerServer) {
	// If the following call panics, it indicates UnimplementedVideoStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoStreamer_ServiceDesc, srv)
}

func _VideoStreamer_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoStreamerServer).UploadVideo(&grpc.GenericServerStream[FrameRequest, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoStreamer_UploadVideoServer = grpc.ClientStreamingServer[FrameRequest, UploadStatus]

// VideoStreamer_ServiceDesc is the grpc.ServiceDesc for VideoStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoStreamer",
	HandlerType: (*VideoStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadVideo",
			Handler:       _VideoStreamer_UploadVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "video.proto",
}
