# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x05video\"\x88\x01\n\x0c\x46rameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x17\n\x0fsequence_number\x18\x04 \x01(\x03\x12\x10\n\x08\x65ncoding\x18\x05 \x01(\t\x12\x12\n\nimage_data\x18\x06 \x01(\x0c\"I\n\x0cUploadStatus\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x0frecommended_fps\x18\x03 \x01(\x05\x32J\n\rVideoStreamer\x12\x39\n\x0bUploadVideo\x12\x13.video.FrameRequest\x1a\x13.video.UploadStatus(\x01\x42\x1cZ\x1asentinel-ai/ingestor-go/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032sentinel-ai/ingestor-go/pb'
  _globals['_FRAMEREQUEST']._serialized_start=23
  _globals['_FRAMEREQUEST']._serialized_end=159
  _globals['_UPLOADSTATUS']._serialized_start=161
  _globals['_UPLOADSTATUS']._serialized_end=234
  _globals['_VIDEOSTREAMER']._serialized_start=236
  _globals['_VIDEOSTREAMER']._serialized_end=310
# @@protoc_insertion_point(module_scope)
